package com.nabil.movienerd.model

import com.nabil.movienerd.R

object FilmDataSource {
    val dummyFilms = listOf(
        Film(0, R.drawable.fight_club, "Fight Club", "David Fincher", "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more. dirilis pada tahun 1999 yang diadaptasi dari novel yang juga berjudul Fight Club karya Chuck Palahniuk. Film ini disutradarai oleh David Fincher dan diperankan oleh Edward Norton (tokoh protagonis dalam film ini yang tanpa nama dan selaku narator). Film yang mengisahkan seorang pria yang terjebak dalam kehidupan sebagai masyarakat pekerja \"kerah putih\" yang terlibat klub pertarungan ilegal yang dirintis oleh penjual sabun yang bernama Tyler Durden (Brad Pitt). Mereka terjerumus dalam kisah segitiga dengan seorang wanita bernama Marla Singer (Helena Bonham Carter)."),
        Film(1, R.drawable.godfather, "Godfather", "Francis Ford Coppola", "nally puts the lives of his loved ones in grave danger. Film ini merupakan film terlaris sepanjang masa yang pernah dibuat, dan tetap menjadi pemimpin box office pada tahun 1972. Film ini berhasil memenangkan tiga Oscar pada tahun itu: Best Picture, Best Actor (Brando) dan kategori Skenario Adaptasi Terbaik untuk Puzo dan Coppola. Nominasi dalam tujuh kategori lainnya termasuk Pacino, James Caan, dan Robert Duvall untuk Aktor Pendukung Terbaik dan Coppola sebagai Sutradara Terbaik. Keberhasilan film ini melahirkan dua film lanjutannya: The Godfather Part II pada tahun 1974, dan The Godfather Part III pada tahun 1990."),
        Film(2, R.drawable.review_img4, "Django", "Quentin Tarantino", "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi. Django Unchained adalah film drama kriminal thriller Amerika Serikat tahun 2012 yang disutradarai oleh Quentin Tarantino dan diproduseri oleh Reginald Hudlin, Stacy Sher dan Pilar Savone. Naskah film ini ditulis oleh Quentin Tarantino. Film ini dibintangi oleh Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington, Samuel L. Jackson dan Walton Goggins.\n" +
                "\n" +
                "Film Django Unchained merupakan film kolaborasi kedua Jamie Foxx dan Kerry Washington setelah film Ray. Film ini ditayangkan secara perdana di Ziegfeld Theatre pada tanggal 11 Desember 2012 dan dirilis di Amerika Serikat pada tanggal 25 Desember 2012.[3][4] Film ini mendapatkan review positif dari para kritikus."),
        Film(3, R.drawable.topgun, "TopGun Maverick", "Joseph Kosinski", "Top Gun: Maverick adalah film drama aksi Amerika mendatang yang disutradarai oleh Joseph Kosinski, diproduksi oleh Jerry Bruckheimer, Tom Cruise dan David Ellison dengan skenario yang ditulis oleh Peter Craig, Justin Marks, Christopher McQuarrie, dan Eric Warren Singer. Ini adalah sekuel Top Gun (1986) dan dibintangi Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm, Glen Powell, Lewis Pullman, dan Ed Harris, dengan Cruise dan Val Kilmer berperan kembali dari film pertama."),
        Film(4, R.drawable.hackshaw, "Hackshaw Ridge", "Mel Gibson", "Hacksaw Ridge adalah film biografi drama perang tahun 2016 yang disutradarai oleh Mel Gibson dan diproduseri oleh Terry Benedict, Paul Currie, Bruce Davey, William D. Johnson, Bill Mechanic, Brian Oliver dan David Permut. Naskah film ini ditulis oleh Andrew Knight dan Robert Schenkkan berdasarkan kisah nyata Desmond Doss menjadi tentara medis Amerika Serikat selama Perang Dunia II. Film ini dibintangi oleh Andrew Garfield, Vince Vaughn, Sam Worthington, Luke Bracey, Teresa Palmer, Hugo Weaving dan Rachel Griffiths."),
        Film(5, R.drawable.review_img5, "Seven", "David Fincher", "Seven (juga ditulis sebagai Se7en) (1995) adalah sebuah film mengenai seorang pembunuh serial yang terobsesi dengan tujuh dosa pokok. Film ini disutradarai oleh David Fincher (filmnya yang kedua) dan ditulis oleh Andrew Kevin Walker yang menerima nominasi Penghargaan BAFTA.\n" +
                "Semboyan: \"Seven deadly sins. Seven ways to die.\" \"Tujuh dosa utama yang mematikan. Tujuh cara untuk mati.\""),
        Film(6, R.drawable.her, "Her", "Spike Jonze", " Her adalah film drama fiksi ilmiah romantis Amerika Serikat tahun 2013 yang disutradarai oleh Spike Jonze dan diproduseri oleh Spike Jonze, Megan Ellison dan Vincent Landay. Naskah film ini ditulis oleh Spike Jonze. Film ini dibintangi oleh Joaquin Phoenix, Scarlett Johansson, Amy Adams, Rooney Mara dan Olivia Wilde.\n" +
                "Film Her merupakan film kolaborasi kedua Joaquin Phoenix dan Amy Adams setelah film The Master. Film ini ditayangkan secara perdana di Festival Film New York pada tanggal 13 Oktober 2013 dan dirilis di Amerika Serikat pada tanggal 18 Desember 2013 secara terbatas dan 10 Januari 2014 secara luas. Film ini mendapatkan review positif dari para kritikus."),
        Film(7, R.drawable.truman, "Trumanshow", "Peter Weir", "The Truman Show adalah film drama-komedi psikologi Amerika Serikat tahun 1998.[1] Film ini digarap oleh Peter Weir dan diproduksi oleh Scott Rudin, Andrew Niccol, Edward S. Feldman, dan Adam Schroeder, dan ditulis oleh Niccol. Film ini dibintangi oleh Jim Carrey sebagai Truman Burbank. Film ini juga diperankan oleh oleh Laura Linney, Noah Emmerich, Natascha McElhone, Holland Taylor, Ed Harris, Paul Giamatti dan Brian Delate. Film ini mengisahkan kehidupan pria bernama Truman Burbank yang kehidupannya direkayasa untuk hiburan dan disiarkan sebagai acara realitas di televisi. Orang-orang di sekeliling Truman sebenarnya adalah aktor yang disewa untuk berperan dalam kehidupan rekayasa tersebut yang tak disadari sama sekali oleh Truman sepanjang hidupnya."),
        Film(8, R.drawable.inception, "Inception", "Christopher Nolan", "Inception adalah film fiksi ilmiah tahun 2010 yang disutradarai oleh Christopher Nolan dan diproduseri oleh Christopher Nolan dan Emma Thomas. Naskah film ini ditulis oleh Christopher Nolan. Film ini dibintangi oleh Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy, Ken Watanabe, Cillian Murphy, Marion Cotillard, Tom Berenger dan Michael Caine.\n" +
                "Film Inception ditayangkan secara perdana di Odeon Leicester Square pada tanggal 8 Juli 2010 dan dirilis di Amerika Serikat dan Britania Raya pada tanggal 16 Juli 2010.[3] Film ini mendapatkan review positif dari para kritikus."),
        Film(9, R.drawable.review_img3, "Baby Driver", "Edgar Wright", "Baby Driver adalah film kriminal kejahatan tahun 2017 yang disutradarai oleh Edgar Wright dan diproduseri oleh Tim Bevan, Eric Fellner dan Nira Park. Naskah film ini ditulis oleh Edgar Wright. Film ini dibintangi oleh Ansel Elgort, Kevin Spacey, Lily James, Jon Bernthal, Eiza González, Jon Hamm dan Jamie Foxx.\n" +
                "Film Baby Driver ditayangkan secara perdana di South by Southwest (SXSW) pada tanggal 11 Maret 2017[5] dan dirilis di Amerika Serikat pada tanggal 28 Juni 2017. Film ini mendapatkan review positif dari para kritikus.")
    )
}